// Generated by scripts/direct-parser/generate.py.
package io.github.gustavo2358.cobolexplorer;

import java.util.*;

/** Syntax bridge only: CICS selects operands; the canonical COBOL grammar parses host references. */
final class DirectCicsHostSyntax {
    record Host(String option,int optionStart,Ast.EmbeddedHostRole role,DirectSyntax.IdentifierFrame identifier) { }
    static List<Host> parse(String raw,int sourceOffset,int sourceLine,int sourceColumn,int anchorToken) {
        var parsed=new CicsProgramControlAnalyzer().parse(raw);
        var file=new CicsFileControlAnalyzer().parse(raw);
        var options=new ArrayList<CicsCommandSyntax.Option>();var roles=new HashMap<Integer,Ast.EmbeddedHostRole>();
        if(parsed.isPresent())for(var option:parsed.get().options()) {
            if(!Set.of("PROGRAM","COMMAREA","CHANNEL","LENGTH","RESP","RESP2","INPUTMSG","INPUTMSGLEN","DATALENGTH","SYSID","TRANSID").contains(option.name()))continue;
            options.add(new CicsCommandSyntax.Option(option.name(),option.operand(),option.start(),option.end()));
            roles.put(option.start(),Set.of("RESP","RESP2").contains(option.name())?Ast.EmbeddedHostRole.WRITE:option.name().equals("COMMAREA")?Ast.EmbeddedHostRole.READ_WRITE:Ast.EmbeddedHostRole.READ);
        }
        if(file.isPresent())for(var option:file.get().options()) {
            if(option.role()==CicsFileControlAnalyzer.Role.NONE)continue;
            options.add(option.syntax());roles.put(option.syntax().start(),switch(option.role()) {
                case WRITE -> Ast.EmbeddedHostRole.WRITE;case READ_WRITE -> Ast.EmbeddedHostRole.READ_WRITE;default -> Ast.EmbeddedHostRole.READ;
            });
        }
        CicsHandlerSyntax.parse(raw).ifPresent(handler->{
            for(var option:handler.options())if(Set.of("PROGRAM","RESP","RESP2").contains(option.name())) {
                options.add(option);roles.put(option.start(),option.name().equals("PROGRAM")?Ast.EmbeddedHostRole.READ:Ast.EmbeddedHostRole.WRITE);
            }
        });
        CicsCommandSemantics.parse(raw).ifPresent(command->{
            for(var option:command.options())if(!option.name().equals("LENGTH")&&(Set.of("MAP","MAPSET","FROM","INTO","RESP","RESP2","TRANSID","COMMAREA").contains(option.name())||CicsCommandSemantics.extra(command.command()).contains(option.name()))) {
                options.add(option);roles.put(option.start(),CicsCommandSemantics.writes(command.command(),option.name())?Ast.EmbeddedHostRole.WRITE:Ast.EmbeddedHostRole.READ);
            }
        });
        var result=new ArrayList<Host>();
        for(var option:options) {
            if(option.operand().isEmpty())continue;
            int begin=option.operandStart();String operand=option.operand().orElseThrow();
            var identifier=parseReference(operand,raw,begin,sourceOffset,sourceLine,sourceColumn,anchorToken).orElse(null);
            if(identifier==null)continue;
            var role=roles.get(option.start());
            result.add(new Host(option.name(),option.start(),role,identifier));
        }
        return List.copyOf(result);
    }
    static boolean supportsReference(String operand,String raw,int begin,int offset,int line,int column,int token){
        return DirectParseScope.active()?DirectCicsHostSyntax.parseReference(operand,raw,begin,offset,line,column,token).isPresent()
            :parseReference(operand,raw,begin,offset,line,column,token).isPresent();
    }
    static Optional<DirectSyntax.IdentifierFrame> parseReference(String operand,String raw,int begin,
            int sourceOffset,int sourceLine,int sourceColumn,int anchorToken) {
        try {
            var identifier=((DirectSyntax.EmbeddedIdentifierFrame)DirectEmbeddedProcedureSyntax.parseRule(operand,"embeddedIdentifier")).identifier();
            if(identifier.qualifiedDataName()==null&&identifier.tableCall()==null)return Optional.empty();
            DirectEmbeddedProcedureSyntax.anchor(identifier,raw,begin,sourceOffset,sourceLine,sourceColumn,anchorToken);
            return Optional.of(identifier);
        } catch(DirectRecognizer.Unsupported e){return Optional.empty();}
    }
}
