// Generated by scripts/direct-parser/generate.py.
package io.github.gustavo2358.cobolexplorer;

import java.util.*;

/** Small host-expression bridge. COBOL grammar owns structure; SourceMap owns source identity. */
final class DirectEmbeddedExpressionSyntax {
    record Parsed(DirectFrame tree) { }
    record Host(String option,int optionStart,DirectFrame tree) { }
    static boolean supported(String text){return parse(text).isPresent();}
    private static Optional<Parsed> parse(String text) {
        try {
            var tokens=DirectLexerBoundary.lex(text);
            var ledger=new DirectRecognizer(tokens).parse(DirectEmbeddedProcedureSyntax.rule(tokens[0].type()==DirectSyntax.INTEGERLITERAL?"literal":"embeddedIdentifier"));
            DirectFrame tree=(DirectFrame)ledger.view(0);
            if(tree instanceof DirectSyntax.EmbeddedIdentifierFrame embedded)tree=embedded.identifier();
            boolean valid=tree instanceof DirectSyntax.LiteralFrame l&&l.numericLiteral()!=null&&l.numericLiteral().integerLiteral()!=null;
            if(tree instanceof DirectSyntax.IdentifierFrame i)valid=i.qualifiedDataName()!=null||i.tableCall()!=null
                ||i.specialRegister()!=null&&i.specialRegister().LENGTH()!=null&&i.specialRegister().identifier()!=null
                  &&(i.specialRegister().identifier().qualifiedDataName()!=null||i.specialRegister().identifier().tableCall()!=null);
            return valid?Optional.of(new Parsed(tree)):Optional.empty();
        }catch(DirectRecognizer.Unsupported e){return Optional.empty();}
    }
    static Optional<DirectFrame> parseAt(String operand,String raw,int begin,int offset,int line,int column,int tokenIndex) {
        var parsed=parse(operand);if(parsed.isEmpty())return Optional.empty();
        DirectEmbeddedProcedureSyntax.anchor(parsed.get().tree(),raw,begin,offset,line,column,tokenIndex);
        return Optional.of(parsed.get().tree());
    }
    static List<Host> parse(String raw,int offset,int line,int column,int tokenIndex) {
        var command=CicsCommandSemantics.parse(raw);
        var options=new ArrayList<CicsCommandSyntax.Option>();
        if(command.filter(c->CicsCommandSemantics.length(c.command())).isPresent())options.addAll(command.get().options());
        // Non-reference LENGTH operands have their own identity; they are not a write to the measured item.
        new CicsFileControlAnalyzer().parse(raw).ifPresent(file->{
            for(var o:file.options())if(o.syntax().name().equals("LENGTH")&&o.syntax().operand().isPresent()) {
                var parsed=parse(o.syntax().operand().orElseThrow());
                if(parsed.isPresent()&&parsed.get().tree() instanceof DirectSyntax.IdentifierFrame i&&i.specialRegister()!=null)options.add(o.syntax());
            }
        });
        var out=new ArrayList<Host>();
        for(var option:options)if(option.name().equals("LENGTH")&&option.operand().isPresent()) {
            var tree=parseAt(option.operand().orElseThrow(),raw,raw.indexOf('(',option.start())+1,offset,line,column,tokenIndex);
            if(tree.isEmpty())continue;
            out.add(new Host(option.name(),option.start(),tree.get()));
        }
        return List.copyOf(out);
    }
}
