       *> Generated by generate-control-signatures.py.
       *> 10 independent choices; 1024 possible BODY inputs.
       *> All calls are reachable; each concrete execution reaches BODY once.
       *> Expected program names: ONE00000 and ZERO0000.
       IDENTIFICATION DIVISION.
       PROGRAM-ID. CTRLFLAGS10.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 INPUT-01 PIC X.
       01 FLAG-01 PIC X(8).
       01 INPUT-02 PIC X.
       01 FLAG-02 PIC X(8).
       01 INPUT-03 PIC X.
       01 FLAG-03 PIC X(8).
       01 INPUT-04 PIC X.
       01 FLAG-04 PIC X(8).
       01 INPUT-05 PIC X.
       01 FLAG-05 PIC X(8).
       01 INPUT-06 PIC X.
       01 FLAG-06 PIC X(8).
       01 INPUT-07 PIC X.
       01 FLAG-07 PIC X(8).
       01 INPUT-08 PIC X.
       01 FLAG-08 PIC X(8).
       01 INPUT-09 PIC X.
       01 FLAG-09 PIC X(8).
       01 INPUT-10 PIC X.
       01 FLAG-10 PIC X(8).
       PROCEDURE DIVISION.
       MAIN.
           PERFORM CHOOSE-01.
           GOBACK.
       CHOOSE-01.
           IF INPUT-01 = 'Y'
               MOVE 'ONE00000' TO FLAG-01
               PERFORM CHOOSE-02
           ELSE
               MOVE 'ZERO0000' TO FLAG-01
               PERFORM CHOOSE-02
           END-IF.
           EXIT.
       CHOOSE-02.
           IF INPUT-02 = 'Y'
               MOVE 'ONE00000' TO FLAG-02
               PERFORM CHOOSE-03
           ELSE
               MOVE 'ZERO0000' TO FLAG-02
               PERFORM CHOOSE-03
           END-IF.
           EXIT.
       CHOOSE-03.
           IF INPUT-03 = 'Y'
               MOVE 'ONE00000' TO FLAG-03
               PERFORM CHOOSE-04
           ELSE
               MOVE 'ZERO0000' TO FLAG-03
               PERFORM CHOOSE-04
           END-IF.
           EXIT.
       CHOOSE-04.
           IF INPUT-04 = 'Y'
               MOVE 'ONE00000' TO FLAG-04
               PERFORM CHOOSE-05
           ELSE
               MOVE 'ZERO0000' TO FLAG-04
               PERFORM CHOOSE-05
           END-IF.
           EXIT.
       CHOOSE-05.
           IF INPUT-05 = 'Y'
               MOVE 'ONE00000' TO FLAG-05
               PERFORM CHOOSE-06
           ELSE
               MOVE 'ZERO0000' TO FLAG-05
               PERFORM CHOOSE-06
           END-IF.
           EXIT.
       CHOOSE-06.
           IF INPUT-06 = 'Y'
               MOVE 'ONE00000' TO FLAG-06
               PERFORM CHOOSE-07
           ELSE
               MOVE 'ZERO0000' TO FLAG-06
               PERFORM CHOOSE-07
           END-IF.
           EXIT.
       CHOOSE-07.
           IF INPUT-07 = 'Y'
               MOVE 'ONE00000' TO FLAG-07
               PERFORM CHOOSE-08
           ELSE
               MOVE 'ZERO0000' TO FLAG-07
               PERFORM CHOOSE-08
           END-IF.
           EXIT.
       CHOOSE-08.
           IF INPUT-08 = 'Y'
               MOVE 'ONE00000' TO FLAG-08
               PERFORM CHOOSE-09
           ELSE
               MOVE 'ZERO0000' TO FLAG-08
               PERFORM CHOOSE-09
           END-IF.
           EXIT.
       CHOOSE-09.
           IF INPUT-09 = 'Y'
               MOVE 'ONE00000' TO FLAG-09
               PERFORM CHOOSE-10
           ELSE
               MOVE 'ZERO0000' TO FLAG-09
               PERFORM CHOOSE-10
           END-IF.
           EXIT.
       CHOOSE-10.
           IF INPUT-10 = 'Y'
               MOVE 'ONE00000' TO FLAG-10
               PERFORM BODY
           ELSE
               MOVE 'ZERO0000' TO FLAG-10
               PERFORM BODY
           END-IF.
           EXIT.
       BODY.
           IF FLAG-01 = 'ONE00000'
               CALL 'ONE00000'
           ELSE
               CALL 'ZERO0000'
           END-IF.
           IF FLAG-02 = 'ONE00000'
               CALL 'ONE00000'
           ELSE
               CALL 'ZERO0000'
           END-IF.
           IF FLAG-03 = 'ONE00000'
               CALL 'ONE00000'
           ELSE
               CALL 'ZERO0000'
           END-IF.
           IF FLAG-04 = 'ONE00000'
               CALL 'ONE00000'
           ELSE
               CALL 'ZERO0000'
           END-IF.
           IF FLAG-05 = 'ONE00000'
               CALL 'ONE00000'
           ELSE
               CALL 'ZERO0000'
           END-IF.
           IF FLAG-06 = 'ONE00000'
               CALL 'ONE00000'
           ELSE
               CALL 'ZERO0000'
           END-IF.
           IF FLAG-07 = 'ONE00000'
               CALL 'ONE00000'
           ELSE
               CALL 'ZERO0000'
           END-IF.
           IF FLAG-08 = 'ONE00000'
               CALL 'ONE00000'
           ELSE
               CALL 'ZERO0000'
           END-IF.
           IF FLAG-09 = 'ONE00000'
               CALL 'ONE00000'
           ELSE
               CALL 'ZERO0000'
           END-IF.
           IF FLAG-10 = 'ONE00000'
               CALL 'ONE00000'
           ELSE
               CALL 'ZERO0000'
           END-IF.
           EXIT.
