// Generated by scripts/direct-parser/generate.py.
package com.imd.cobolexplorer;

import java.util.*;

/** Native N-LR syntax facts. Uses parser identities, never statement text or runtime assumptions. */
final class DirectFileIoSyntax {
    private DirectFileIoSyntax() { }
    static boolean isNativeStatement(DirectSyntax.StatementFrame c) {
        return c.openStatement()!=null||c.closeStatement()!=null||c.readStatement()!=null||c.writeStatement()!=null
            ||c.rewriteStatement()!=null||c.deleteStatement()!=null||c.startStatement()!=null
            ||c.releaseStatement()!=null||c.returnStatement()!=null||c.sortStatement()!=null||c.mergeStatement()!=null;
    }
    static List<DirectFrame> handlerContexts(DirectSyntax.StatementFrame root) {
        var result=new ArrayList<DirectFrame>();var pending=new ArrayDeque<DirectSpan>();
        for(int i=0;i<root.getChildCount();i++)pending.addLast(root.getChild(i));
        while(!pending.isEmpty()) {
            var node=pending.removeFirst();if(node instanceof DirectSyntax.StatementFrame)continue;
            if(node instanceof DirectSyntax.AtEndPhraseFrame||node instanceof DirectSyntax.NotAtEndPhraseFrame
                ||node instanceof DirectSyntax.InvalidKeyPhraseFrame||node instanceof DirectSyntax.NotInvalidKeyPhraseFrame
                ||node instanceof DirectSyntax.WriteAtEndOfPagePhraseFrame||node instanceof DirectSyntax.WriteNotAtEndOfPagePhraseFrame) {
                result.add((DirectFrame)node);continue;
            }
            for(int i=0;i<node.getChildCount();i++)pending.addLast(node.getChild(i));
        }
        return List.copyOf(result);
    }

    static Ast.FileOperandRole operandRole(DirectFrame root, DirectFrame operand) {
        if (command(root)==null) return null;
        if (operand instanceof DirectSyntax.RecordNameFrame) return Ast.FileOperandRole.RECORD;
        if(root instanceof DirectSyntax.ReleaseStatementFrame&&operand instanceof DirectSyntax.QualifiedDataNameFrame)return Ast.FileOperandRole.FROM;
        for(var p=operand.getParent();p!=null&&p!=root;p=p.getParent()) {
            if(p instanceof DirectSyntax.ReadIntoFrame||p instanceof DirectSyntax.ReturnIntoFrame)return Ast.FileOperandRole.INTO;
            if(p instanceof DirectSyntax.ReadKeyFrame || p instanceof DirectSyntax.StartKeyFrame)return Ast.FileOperandRole.KEY;
            if(p instanceof DirectSyntax.SortOnKeyClauseFrame||p instanceof DirectSyntax.MergeOnKeyClauseFrame)return Ast.FileOperandRole.KEY;
            if(p instanceof DirectSyntax.WriteFromPhraseFrame || p instanceof DirectSyntax.RewriteFromFrame)return Ast.FileOperandRole.FROM;
            if(p instanceof DirectSyntax.WriteAdvancingPhraseFrame)return Ast.FileOperandRole.ADVANCING;
        }
        return null;
    }
    static boolean tableSort(DirectSyntax.SortStatementFrame s){return s.sortUsing().isEmpty()&&s.sortGivingPhrase().isEmpty()&&s.sortInputProcedurePhrase()==null&&s.sortOutputProcedurePhrase()==null;}
    private static Ast.FileCommand command(DirectFrame c) {
        if(c instanceof DirectSyntax.OpenStatementFrame)return Ast.FileCommand.OPEN;
        if(c instanceof DirectSyntax.ReadStatementFrame)return Ast.FileCommand.READ;
        if(c instanceof DirectSyntax.WriteStatementFrame)return Ast.FileCommand.WRITE;
        if(c instanceof DirectSyntax.RewriteStatementFrame)return Ast.FileCommand.REWRITE;
        if(c instanceof DirectSyntax.DeleteStatementFrame)return Ast.FileCommand.DELETE_RECORD;
        if(c instanceof DirectSyntax.StartStatementFrame)return Ast.FileCommand.START;
        if(c instanceof DirectSyntax.CloseStatementFrame)return Ast.FileCommand.CLOSE;
        if(c instanceof DirectSyntax.ReleaseStatementFrame)return Ast.FileCommand.RELEASE;
        if(c instanceof DirectSyntax.ReturnStatementFrame)return Ast.FileCommand.RETURN;
        if(c instanceof DirectSyntax.SortStatementFrame s&&!tableSort(s))return Ast.FileCommand.SORT;
        if(c instanceof DirectSyntax.MergeStatementFrame)return Ast.FileCommand.MERGE;
        return null;
    }
    static Optional<Ast.FileIoSurface> project(DirectFrame c, Map<DirectFrame,Ast.Node> nodes,
            List<DirectFrame> contexts,List<Ast.StatementClause> clauses) {
        var command=command(c);if(command==null)return Optional.empty();
        var profile=Ast.FileSyntaxProfile.N_LR;
        if(c instanceof DirectSyntax.ReadStatementFrame r && r.readWith()!=null)profile=Ast.FileSyntaxProfile.UNSUPPORTED;
        if(c instanceof DirectSyntax.CloseStatementFrame x && x.closeFile().stream().anyMatch(f->f.closePortFileIOStatement()!=null))profile=Ast.FileSyntaxProfile.UNSUPPORTED;
        if(c instanceof DirectSyntax.WriteStatementFrame w && w.writeFromPhrase()!=null && w.writeFromPhrase().literal()!=null)profile=Ast.FileSyntaxProfile.UNSUPPORTED;
        var files=new ArrayList<Ast.FileIoOperand>();var operands=new ArrayList<Ast.FileDataOperand>();var procedures=new ArrayList<Ast.FileProcedureSurface>();var gaps=new ArrayList<String>();
        // Identity map iteration is not semantic order. DirectToken positions are unique among these operand roots.
        var entries=new ArrayList<>(nodes.entrySet());entries.sort(Comparator.comparingInt(e->e.getKey().getStart().getTokenIndex()));
        for(var e:entries) {
            var role=operandRole(c,e.getKey());if(role!=null)operands.add(new Ast.FileDataOperand(role,e.getValue()));
            if(e.getKey() instanceof DirectSyntax.FileNameFrame || role==Ast.FileOperandRole.RECORD) {
                var mode=Ast.FileOpenMode.UNSPECIFIED;var options=new ArrayList<Ast.FileOption>();
                var fileRole=command==Ast.FileCommand.SORT||command==Ast.FileCommand.MERGE?Ast.FileRole.WORK:Ast.FileRole.DIRECT;
                for(var p=e.getKey().getParent();p!=null&&p!=c;p=p.getParent()) {
                    if(p instanceof DirectSyntax.OpenInputStatementFrame)mode=Ast.FileOpenMode.INPUT;
                    else if(p instanceof DirectSyntax.OpenOutputStatementFrame)mode=Ast.FileOpenMode.OUTPUT;
                    else if(p instanceof DirectSyntax.OpenIOStatementFrame)mode=Ast.FileOpenMode.IO;
                    else if(p instanceof DirectSyntax.OpenExtendStatementFrame)mode=Ast.FileOpenMode.EXTEND;
                    if(p instanceof DirectSyntax.SortUsingFrame||p instanceof DirectSyntax.MergeUsingFrame){fileRole=Ast.FileRole.INPUT;mode=Ast.FileOpenMode.INPUT;}
                    if(p instanceof DirectSyntax.SortGivingFrame||p instanceof DirectSyntax.MergeGivingFrame){fileRole=Ast.FileRole.OUTPUT;mode=Ast.FileOpenMode.OUTPUT;if(p.getChildCount()>1)profile=Ast.FileSyntaxProfile.UNSUPPORTED;}
                    if(p instanceof DirectSyntax.OpenInputFrame || p instanceof DirectSyntax.OpenOutputFrame) options.addAll(options(p));
                    if(p instanceof DirectSyntax.CloseFileFrame f) {
                        if(f.closeRelativeStatement()!=null)options.addAll(options(f.closeRelativeStatement()));
                        if(f.closeReelUnitStatement()!=null)options.addAll(options(f.closeReelUnitStatement()));
                    }
                }
                files.add(new Ast.FileIoOperand(e.getValue(),mode,options,fileRole));
            }
        }
        var options=new ArrayList<Ast.FileOption>();var relation=Ast.FileKeyRelation.UNSPECIFIED;
        boolean terminated=false;
        if(c instanceof DirectSyntax.ReadStatementFrame r){if(r.NEXT()!=null)options.add(Ast.FileOption.NEXT);terminated=r.END_READ()!=null;}
        if(c instanceof DirectSyntax.ReturnStatementFrame r)terminated=r.END_RETURN()!=null;
        if(c instanceof DirectSyntax.DeleteStatementFrame d)terminated=d.END_DELETE()!=null;
        if(c instanceof DirectSyntax.RewriteStatementFrame r)terminated=r.END_REWRITE()!=null;
        if(c instanceof DirectSyntax.StartStatementFrame s) {
            terminated=s.END_START()!=null;var key=s.startKey();relation=Ast.FileKeyRelation.EQUAL;
            if(key!=null) {
                if(key.NOT()!=null || key.MORETHANOREQUAL()!=null || key.OR()!=null)relation=Ast.FileKeyRelation.GREATER_OR_EQUAL;
                else if(key.GREATER()!=null || key.MORETHANCHAR()!=null)relation=Ast.FileKeyRelation.GREATER;
            }
        }
        if(c instanceof DirectSyntax.WriteStatementFrame w) {
            terminated=w.END_WRITE()!=null;var adv=w.writeAdvancingPhrase();
            if(adv!=null){options.add(adv.BEFORE()!=null?Ast.FileOption.BEFORE_ADVANCING:Ast.FileOption.AFTER_ADVANCING);if(adv.writeAdvancingPage()!=null)options.add(Ast.FileOption.PAGE);}
        }
        var handlers=new ArrayList<Ast.FileHandler>();
        for(int i=0;i<contexts.size();i++) {
            var h=contexts.get(i);Ast.FileHandlerKind kind=null;
            if(h instanceof DirectSyntax.AtEndPhraseFrame)kind=Ast.FileHandlerKind.AT_END;
            else if(h instanceof DirectSyntax.NotAtEndPhraseFrame)kind=Ast.FileHandlerKind.NOT_AT_END;
            else if(h instanceof DirectSyntax.InvalidKeyPhraseFrame)kind=Ast.FileHandlerKind.INVALID_KEY;
            else if(h instanceof DirectSyntax.NotInvalidKeyPhraseFrame)kind=Ast.FileHandlerKind.NOT_INVALID_KEY;
            else if(h instanceof DirectSyntax.WriteAtEndOfPagePhraseFrame)kind=Ast.FileHandlerKind.AT_END_OF_PAGE;
            else if(h instanceof DirectSyntax.WriteNotAtEndOfPagePhraseFrame)kind=Ast.FileHandlerKind.NOT_AT_END_OF_PAGE;
            if(kind!=null)handlers.add(new Ast.FileHandler(kind,clauses.get(i)));
        }
        if(c instanceof DirectSyntax.SortStatementFrame s) {
            if(s.sortInputProcedurePhrase()!=null){var p=s.sortInputProcedurePhrase();procedures.add(procedure(Ast.FileProcedurePhase.INPUT,p.procedureName(),p.sortInputThrough()==null?null:p.sortInputThrough().procedureName(),nodes));}
            if(s.sortOutputProcedurePhrase()!=null){var p=s.sortOutputProcedurePhrase();procedures.add(procedure(Ast.FileProcedurePhase.OUTPUT,p.procedureName(),p.sortOutputThrough()==null?null:p.sortOutputThrough().procedureName(),nodes));}
            if(s.sortOnKeyClause().isEmpty()||s.fileName()==null)gaps.add("FILE_SORT_FORMAT_NOT_PROVEN");
        }
        if(c instanceof DirectSyntax.MergeStatementFrame m&&m.mergeOutputProcedurePhrase()!=null){var p=m.mergeOutputProcedurePhrase();procedures.add(procedure(Ast.FileProcedurePhase.OUTPUT,p.procedureName(),p.mergeOutputThrough()==null?null:p.mergeOutputThrough().procedureName(),nodes));}
        if(command==Ast.FileCommand.SORT||command==Ast.FileCommand.MERGE) {
            long inputs=files.stream().filter(f->f.role()==Ast.FileRole.INPUT).count(),outputs=files.stream().filter(f->f.role()==Ast.FileRole.OUTPUT).count();
            boolean inputProc=procedures.stream().anyMatch(p->p.phase()==Ast.FileProcedurePhase.INPUT),outputProc=procedures.stream().anyMatch(p->p.phase()==Ast.FileProcedurePhase.OUTPUT);
            if((inputs>0)==inputProc||(outputs>0)==outputProc||command==Ast.FileCommand.MERGE&&inputs<2)gaps.add("FILE_SORT_PHASES_NOT_PROVEN");
        }
        return Optional.of(new Ast.FileIoSurface(command,files,profile,operands,options,relation,terminated,handlers,procedures,gaps));
    }
    private static Ast.FileProcedureSurface procedure(Ast.FileProcedurePhase phase,DirectFrame start,DirectFrame end,Map<DirectFrame,Ast.Node> nodes){return new Ast.FileProcedureSurface(phase,(Ast.ProcedureReference)nodes.get(start),Optional.ofNullable(end).map(e->(Ast.ProcedureReference)nodes.get(e)));}
    private static List<Ast.FileOption> options(DirectFrame c) {
        var out=new ArrayList<Ast.FileOption>();
        if(c.getToken(DirectSyntax.REVERSED,0)!=null)out.add(Ast.FileOption.REVERSED);
        if(c.getToken(DirectSyntax.REWIND,0)!=null)out.add(Ast.FileOption.NO_REWIND);
        if(c.getToken(DirectSyntax.LOCK,0)!=null)out.add(Ast.FileOption.LOCK);
        if(c.getToken(DirectSyntax.REEL,0)!=null)out.add(Ast.FileOption.REEL);
        if(c.getToken(DirectSyntax.UNIT,0)!=null)out.add(Ast.FileOption.UNIT);
        if(c.getToken(DirectSyntax.REMOVAL,0)!=null)out.add(Ast.FileOption.FOR_REMOVAL);
        return out;
    }
}
