#!/usr/bin/env python3
"""Compile the existing grammar into independent recognition tables and typed spans.
No ANTLR parser/runtime is used by this compiler or its generated recognizer.
The lexer token vocabulary is the only generated-lexer input.
"""
from pathlib import Path
import re, hashlib, sys
from collections import Counter
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'src/main/java/com/imd/cobolexplorer'
CHECK='--check' in sys.argv
def emit(path,text):
    if CHECK:
        if not path.exists() or path.read_text()!=text:raise SystemExit('Stale generated source: '+str(path))
    else:path.write_text(text)
grammar=(ROOT/'src/main/antlr4/Cobol.g4').read_text()
s=grammar[:grammar.index('// lexer rules')]
s=re.sub(r'/\*.*?\*/|//[^\n]*','',s,flags=re.S)
s=re.sub(r'@parser::members\s*\{.*?\}\s*','',s,flags=re.S)
s=re.sub(r'\{[^{}]*\}','',s)
rules=dict(re.findall(r'\b([a-z]\w*)\s*:\s*(.*?);',s,re.S))
names=list(rules); ids={n:i for i,n in enumerate(names)}
vocab=dict((n,int(v)) for n,v in re.findall(r'(?m)^(\w+)=([0-9]+)$',(ROOT/'target/generated-sources/antlr4/Cobol.tokens').read_text()))
vocab['EOF']=-1
# Nodes: empty, terminal, call, sequence, choice, optional, zero-or-more, one-or-more.
nodes=[]; intern={}
def node(kind,*args):
    key=(kind,)+args
    if key not in intern:intern[key]=len(nodes);nodes.append(key)
    return intern[key]
class Grammar:
    def __init__(self,s):
        self.ts=re.findall(r'\w+|[()|?*+]',s);self.p=0
        assert ''.join(self.ts)==re.sub(r'\s+','',s),s
    def take(self):t=self.ts[self.p];self.p+=1;return t
    def peek(self):return self.ts[self.p] if self.p<len(self.ts) else None
    def alt(self):
        out=[self.seq()]
        while self.peek()=='|':self.take();out.append(self.seq())
        return out[0] if len(out)==1 else node(4,*out)
    def seq(self):
        out=[]
        while self.peek() not in (None,')','|'):
            t=self.take()
            if t=='(':
                x=self.alt();assert self.take()==')'
            elif t in ids:x=node(2,ids[t])
            else:x=node(1,vocab[t])
            if self.peek() in ('?','*','+'):
                q=self.take();x=node({'?':5,'*':6,'+':7}[q],x)
            out.append(x)
        return node(0) if not out else out[0] if len(out)==1 else node(3,*out)
roots=[Grammar(rules[n]).alt() for n in names]
first=[set() for _ in nodes];nullable=[False]*len(nodes)
while True:
    changed=False
    for i,(k,*a) in enumerate(nodes):
        f=set();z=False
        if k==0:z=True
        elif k==1:f={a[0]}
        elif k==2:f=first[roots[a[0]]];z=nullable[roots[a[0]]]
        elif k==3:
            z=True
            for x in a:
                f|=first[x]
                if not nullable[x]:z=False;break
        elif k==4:
            for x in a:f|=first[x];z|=nullable[x]
        else:f=first[a[0]];z=k in (5,6) or nullable[a[0]]
        if f!=first[i] or z!=nullable[i]:first[i]=set(f);nullable[i]=z;changed=True
    if not changed:break
header='package com.imd.cobolexplorer;\n\n// Generated by scripts/direct-parser/generate.py. Do not edit.\n'
def write(name,text):emit(OUT/(name+'.java'),header+text)
# Compact encoded rows avoid the JVM 64KiB static initializer limit.
rows=[' '.join(map(str,(8,*(nodes[x][1] for x in n[1:])) if n[0]==4 and all(nodes[x][0]==1 for x in n[1:]) else n)) for n in nodes]
bits=[]
for f in first:
    b=0
    for t in f:b|=1<<(t+1)
    bits.append(format(b,'x'))
write('DirectGrammar','final class DirectGrammar {\n'+
      ' static final String GRAMMAR_SHA256="'+hashlib.sha256(grammar.encode()).hexdigest()+'";\n'+
      ' static final int ARGUMENT='+str(roots[ids['argument']])+', INSPECT_ITEM='+str(roots[ids['inspectAllLeading']])+', IDENTIFIER='+str(roots[ids['identifier']])+', QUALIFIED='+str(roots[ids['qualifiedDataName']])+', ARITHMETIC='+str(roots[ids['arithmeticExpression']])+', IDENTIFIER_RULE='+str(ids['identifier'])+', QUALIFIED_RULE='+str(ids['qualifiedDataName'])+', QUALIFIER='+str(roots[ids['qualifiedInData']])+';\n'+
      ' static final int PARAGRAPH='+str(roots[ids['paragraph']])+', SECTION_HEADER='+str(roots[ids['procedureSectionHeader']])+';\n'+
      ' static final String[] NAMES={'+','.join('"'+n+'"' for n in names)+'};\n'+
      ' static final int[] ROOTS={'+','.join(map(str,roots))+'};\n'+
      ' static final int[][] CODE=decode(new String[]{\n'+',\n'.join('"'+r+'"' for r in rows)+'});\n'+
      ' static final long[][] FIRST=first(new String[]{\n'+',\n'.join('"'+b+'"' for b in bits)+'});\n'+
      ' static final boolean[] NULLABLE=nullable("'+''.join('1' if v else '0' for v in nullable)+'");\n'+
      ''' private static int[][] decode(String[] rows){return java.util.Arrays.stream(rows).map(r->java.util.Arrays.stream(r.split(" ")).mapToInt(Integer::parseInt).toArray()).toArray(int[][]::new);}
 private static long[][] first(String[] rows){long[][] out=new long[rows.length][];for(int i=0;i<rows.length;i++){var b=new java.math.BigInteger(rows[i],16);out[i]=new long[(b.bitLength()+63)/64];for(int j=0;j<out[i].length;j++)out[i][j]=b.shiftRight(j*64).longValue();}return out;}
 private static boolean[] nullable(String s){boolean[] out=new boolean[s.length()];for(int i=0;i<out.length;i++)out[i]=s.charAt(i)=='1';return out;}
 static boolean starts(int expression,int token){int bit=token+1;var bits=FIRST[expression];return bit>=0&&bit/64<bits.length&&(bits[bit/64]&(1L<<(bit%64)))!=0;}
}\n''')
# Only immediate constituents of each production get accessors. Repetition controls multiplicity.
def members(expr):
    k,*a=nodes[expr]
    if k in (1,2):return Counter({(k,a[0]):1})
    if k in (5,6,7):return Counter({n:min(2,v*(2 if k!=5 else 1)) for n,v in members(a[0]).items()})
    out=Counter()
    for x in a if k in (3,4) else []:
        c=members(x)
        for n,v in c.items():out[n]=min(2,out[n]+v) if k==3 else max(out[n],v)
    return out
rev={v:k for k,v in vocab.items()}
def typename(n):return n[0].upper()+n[1:]+'Frame'
parts=['final class DirectSyntax {']
for n,v in vocab.items():parts.append(f' static final int {n}={v};')
parts.append(' static DirectFrame frame(DirectLedger l,int i){return switch(l.rules[i]){')
for i,n in enumerate(names):parts.append(f' case {i} -> new {typename(n)}(l,i);')
parts.append(' default -> throw new IllegalArgumentException();};}')
for i,n in enumerate(names):
    cl=typename(n);parts.append(f' static final class {cl} extends DirectFrame {{ {cl}(DirectLedger l,int i){{super(l,i);}}')
    for (k,a),count in sorted(members(roots[i]).items()):
        if k==2:
            name=names[a];t=typename(name);expr=f'child({t}.class,0)';ls=f'children({t}.class)';nth=f'child({t}.class,n)'
        else:
            name=rev[a];t='DirectTerminal';expr=f'getToken({a},0)';ls=f'getTokens({a})';nth=f'getToken({a},n)'
        if count>1:
            parts.append(f' java.util.List<{t}> {name}(){{return {ls};}}')
            parts.append(f' {t} {name}(int n){{return {nth};}}')
        else:parts.append(f' {t} {name}(){{return {expr};}}')
    parts.append(' }')
parts.append('}')
write('DirectSyntax','\n'.join(parts)+'\n')
print(f'{len(names)} productions, {len(nodes)} expressions')
# Preserve the existing semantic rules while replacing their syntax dependency.
# These are generated actions, not a runtime bridge to the legacy visitor.
def lower(text):
    text=re.sub(r'^import (?:com\.imd\.cobolexplorer\.antlr\.|org\.antlr\.)[^;]*;\s*','',text,flags=re.M)
    text=text.replace('org.antlr.v4.runtime.tree.ParseTree','DirectSpan')
    text=re.sub(r'CobolParser\.(\w+)Context',r'DirectSyntax.\1Frame',text)
    for a,b in [('ParserRuleContext','DirectFrame'),('ParseTree','DirectSpan'),('TerminalNode','DirectTerminal'),('CobolParser.','DirectSyntax.'),('Token','DirectToken')]:
        text=re.sub(r'\b'+re.escape(a)+r'\b',b,text) if not a.endswith('.') else text.replace(a,b)
    # Public AST provenance names remain the versioned contract.
    text=text.replace('Ast.DirectSpanOrigin','Ast.ParseTreeOrigin')
    text=text.replace('@Override','')
    return text
s=(OUT/'AstBuilder.java').read_text()
s=re.sub(r'    AstBuilder\(Parser parser,.*?\n    AstBuildResult build\(','''    DirectAstActions(DirectLedger ledger, String source, SourceMap sourceMap, boolean inputIntegrityKnown) {
        this.ledger=ledger;
        this.indexedSource=new UnicodeText(source);
        this.sourceMap=sourceMap;
        this.inputIntegrityKnown=inputIntegrityKnown && source.equals(sourceMap.text());
    }

    AstBuildResult build(''',s,flags=re.S)
s=re.sub(r'        if \(parser.directDataSession != null\) \{.*?\n        List<Ast.Node> sections', '        List<Ast.Node> sections',s,flags=re.S)
s=s.replace('extends CobolBaseVisitor<Ast.Node>','')
s=s.replace('    private final CobolParser parser;','    private final DirectLedger ledger;')
s=re.sub(r'    private final IdentityHashMap<ParseTree, Integer> parse(?:Ids|SubtreeSizes);\n','',s)
s=s.replace(' || parser.getNumberOfSyntaxErrors() != 0','').replace(' || root.EOF() instanceof ErrorNode','')
s=s.replace('parser.getRuleNames()','DirectGrammar.NAMES')
s=s.replace('!parseIds.containsKey(context)','context.ledger != ledger').replace('parseIds.getOrDefault(context, -1)','context.ledger == ledger ? context.id : -1').replace('parseSubtreeSizes.getOrDefault(context, 1)','context.ledger == ledger ? context.ledger.next[context.id] - context.id : 1')
s=s.replace('AstBuilder','DirectAstActions')
s=lower(s)
# Direct methods over typed spans; wrapper reduction preserves the canonical invariant.
methods=re.findall(r'public Ast.Node (visit\w+)\(DirectSyntax\.(\w+)Frame (\w+)\)',s)
dispatch='''
    private Ast.Node visit(DirectSpan span) {
        if (!(span instanceof DirectFrame frame)) return null;
        switch(frame.getRuleIndex()) {
'''
for method,name,arg in methods:
    rule=name[0].lower()+name[1:]
    dispatch+=f'            case {ids[rule]}: return {method}((DirectSyntax.{name}Frame)frame);\n'
dispatch+='''            default:
                Ast.Node result=null;
                for(int i=0;i<frame.getChildCount();i++) result=aggregateResult(result,visit(frame.getChild(i)));
                return result;
        }
    }
'''
s=s[:s.rfind('}')]+dispatch+'}\n'
for name in ['FileAuxiliarySyntax','FileIoSyntax','CicsHostSyntax','EmbeddedExpressionSyntax','EmbeddedProcedureSyntax']:
    s=s.replace(name,'Direct'+name)
# Pure command parsers retain canonical types; only their syntax bridges are replaced.
s=s.replace('CicsHandlerSyntax.label(', 'DirectEmbeddedProcedureSyntax.handlerLabel(')
s=s.replace('CicsConditionSyntax.label(', 'DirectEmbeddedProcedureSyntax.conditionLabel(')
s=s.replace('Builds one immutable semantic AST from the ANTLR parse tree.','Canonical semantic actions over the independent parser\'s compact production spans.')
emit(OUT/'DirectAstActions.java','// Generated by scripts/direct-parser/generate.py from canonical semantic actions.\n'+s)
for name in ['FileAuxiliarySyntax','FileIoSyntax']:
    s=lower((OUT/(name+'.java')).read_text()).replace(name,'Direct'+name)
    s=s.replace('if(c.children!=null)for(var child:c.children)if(child instanceof DirectFrame p)walk(p,out);','for(int i=0;i<c.getChildCount();i++)if(c.getChild(i) instanceof DirectFrame p)walk(p,out);')
    emit(OUT/('Direct'+name+'.java'),'// Generated by scripts/direct-parser/generate.py.\n'+s)
s=lower((OUT/'CicsHostSyntax.java').read_text()).replace('CicsHostSyntax','DirectCicsHostSyntax').replace('DirectDirectCicsHostSyntax','DirectCicsHostSyntax')
a=s.index('        var lexer=',s.index('static Optional<'))
s=s[:a]+'''        try {
            var identifier=((DirectSyntax.EmbeddedIdentifierFrame)DirectEmbeddedProcedureSyntax.parseRule(operand,"embeddedIdentifier")).identifier();
            if(identifier.qualifiedDataName()==null&&identifier.tableCall()==null)return Optional.empty();
            DirectEmbeddedProcedureSyntax.anchor(identifier,raw,begin,sourceOffset,sourceLine,sourceColumn,anchorToken);
            return Optional.of(identifier);
        } catch(DirectRecognizer.Unsupported e){return Optional.empty();}
    }
}
'''
emit(OUT/'DirectCicsHostSyntax.java','// Generated by scripts/direct-parser/generate.py.\n'+s)
s=lower((OUT/'EmbeddedExpressionSyntax.java').read_text()).replace('EmbeddedExpressionSyntax','DirectEmbeddedExpressionSyntax')
s=s.replace('record Parsed(DirectFrame tree,CommonTokenStream tokens)', 'record Parsed(DirectFrame tree)')
s=re.sub(r'static boolean supported\(String text\)\{[^}]*\}', 'static boolean supported(String text){return parse(text).isPresent();}',s)
a=s.index('        var failed=',s.index('private static Optional<Parsed> parse'))
b=s.index('            boolean valid=',a)
s=s[:a]+'''        try {
            var tokens=DirectLexerBoundary.lex(text);
            var ledger=new DirectRecognizer(tokens).parse(DirectEmbeddedProcedureSyntax.rule(tokens[0].type()==DirectSyntax.INTEGERLITERAL?"literal":"embeddedIdentifier"));
            DirectFrame tree=(DirectFrame)ledger.view(0);
            if(tree instanceof DirectSyntax.EmbeddedIdentifierFrame embedded)tree=embedded.identifier();
'''+s[b:]
s=s.replace('new Parsed(tree,tokens)','new Parsed(tree)')
s=s.replace('org.antlr.v4.runtime.misc.ParseCancellationException','DirectRecognizer.Unsupported')
a=s.index('        for(var token:parsed.get().tokens().getTokens())')
b=s.index('        return Optional.of(parsed.get().tree());',a)
s=s[:a]+'''        DirectEmbeddedProcedureSyntax.anchor(parsed.get().tree(),raw,begin,offset,line,column,tokenIndex);
'''+s[b:]
emit(OUT/'DirectEmbeddedExpressionSyntax.java','// Generated by scripts/direct-parser/generate.py.\n'+s)
